### ISSUE TITLE
No module named 'pandas'

### ISSUE THREAD

**Issue by kitchell** [filipinascimento/bl-network-visualization#7]
Hello, trying to run this on brainlife and I ran into the following error:

Traceback (most recent call last):
  File "/N/dc2/scratch/brlife/carbonate-workflows/5f3d40df590dea782294cc58/5f3e8d1b590dea49c694d511/main.py", line 15, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

The app ran on the IU carbonate resource.

**Comment by filipinascimento** [comment]
Thanks for the issue. This was corrected in the docker image. The package `pandas` was missing. https://github.com/filipinascimento/cxnetworks-docker/commit/51f8c4ac7611e2591a19a5864ae4c2db48f0a98a
